---
- hosts: localhost
  become: True
  tasks:
    - name: Install boto3
      yum:
        name: boto3
        state: present 
    - name: Create S3 bucket
      s3_bucket: 
        name: javahome-tf-1212-bk
        state: present
...

